name: Docker Build

on:
  push:
    branches:
      - master
# 仅允许管理员手动执行
permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up temporary directory
        run: |
          mkdir -p ${{ github.workspace }}/tmp
          echo ${{ github.workspace }}/tmp > run.log

      - name: Build and push Docker images
        run: |
          cd docker
          chmod +x build-and-push.sh
          script_output=$(bash ./build-and-push.sh 2>&1)
          echo "$script_output" > ${{ github.workspace }}/tmp/run.log

      - name: Display script output
        run: |
          cat ${{ github.workspace }}/tmp/run.log
          rm -rf /tmp/run.log